---
timezone_region: Europe/Oslo
frikanalen_app_namespace: default
frikanalen_public_ingress_class: public

frikanalen_domain: frikanalen.no
frikanalen_scheme: https

caspar_host: "192.168.3.34"

django_db_host: django-postgres
django_db_secret_name: django-postgres-passwords

traefik_acme_challenge: web # we don't use DNS01 in prod (yet?)

app_versions:
  graphics: v1.0.0
  playout: v1.0.2
  frontend: v2.0.4
  django: v0.1.2

helm_chart_versions:
  traefik: "37.4.0"
  argocd: "9.1.7"
  external_dns: "1.19.0"
  metallb: "0.15.3"
  kubegres: "v1.19"

