---
timezone_region: Europe/Oslo
frikanalen_app_namespace: default
frikanalen_public_ingress_class: public

frikanalen_domain: frikanalen.no
frikanalen_scheme: https

caspar_host: "192.168.3.35"

django_db_host: django-postgres
django_db_secret_name: django-postgres-passwords

traefik_acme_challenge: web # we don't use DNS01 in prod (yet?)

argocd_stream_cubemap_ip: "192.168.3.105"

app_versions:
  graphics: staging
  playout: staging
  frontend: v2.0.4
  django: v0.1.2
  stream: main

helm_chart_versions:
  traefik: "37.4.0"
  argocd: "9.1.7"
  external_dns: "1.19.0"
  metallb: "0.15.3"
  kubegres: "v1.19"

