---
frikanalen_domain: staging.frikanalen.no
frikanalen_scheme: https
frikanalen_base_url: "{{ frikanalen_scheme }}://{{ frikanalen_domain }}"

caspar_host: "192.168.3.34"

django_db_host: django-postgres
django_db_secret_name: django-postgres-passwords

app_versions:
  graphics: staging
  playout: staging
  frontend: staging
  django: staging
