---

# Zone we are managing
dns_zone_name: "dc1.frikanalen.no"

# SOA defaults
dns_soa_mname: "ns1.{{ dns_zone_name }}."
dns_soa_rname: "hostmaster.{{ dns_zone_name }}."
dns_soa_serial: "{{ '%Y%m%d%H' | strftime }}"
dns_soa_refresh: 3600
dns_soa_retry: 900
dns_soa_expire: 604800
dns_soa_minimum: 86400

# Name server(s) we want to advertise
dns_ns_records:
  - "ns1.{{ dns_zone_name }}."

# IP of the DNS server itself (for NS A record)
dns_ns1_address: "192.168.3.2"

# Reverse zones we want to generate from the hosts.yml
dns_reverse_prefixes:
  - "192.168.3"
  - "192.168.4"

# Public IP address for externally-facing zones (staging.frikanalen.no)
dns_ns1_public_address: "158.36.191.229"

# Paths are for BIND installed from pkg/ports on FreeBSD.
dns_zone_dir: "/usr/local/etc/namedb/master"
dns_named_conf_d: "/usr/local/etc/namedb/named.conf.d"
