---
traefik_namespace: traefik
traefik_chart_version: "{{ helm_chart_versions.traefik }}"

# ACME/Let's Encrypt configuration
traefik_acme_email: toresbe@protonmail.com
traefik_acme_storage: /data/acme.json
traefik_acme_challenge: dns # 'dns' for RFC2136 or 'http' for HTTP-01

# Service configuration
traefik_service_type: LoadBalancer

# Dashboard
traefik_dashboard_enabled: true

# Ingress class for external-dns integration
traefik_ingress_class: public

# RFC2136 DNS challenge defaults (same as external_dns)
# Only relevant if traefik_acme_challenge is 'dns'
traefik_rfc2136_host: "192.168.3.2"
traefik_rfc2136_port: "53"
traefik_rfc2136_tsig_keyname: "staging-update-key"
traefik_rfc2136_tsig_algorithm: "hmac-sha256"

