---
users:
    - username: toresbe
      realname: "Tore Sinding Bekkedal"
      ssh_keys: |
        ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHxuTVYGn/cJtTZGComq/Gg0BQREWOEFy5682snA61og Tore Frikanalen 2025
